# Generated by Django 4.2.26 on 2025-11-23 22:17

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Cognome')),
                ('ruolo', models.CharField(choices=[('ADMIN', 'Amministratore'), ('CONSULENTE', 'Consulente'), ('REFERENTE', 'Referente Aziendale'), ('STUDENTE', 'Studente/Dipendente')], default='STUDENTE', max_length=15, verbose_name='Ruolo')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome Azienda')),
                ('partita_iva', models.CharField(max_length=20, unique=True, verbose_name='Partita IVA')),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indirizzo Sede')),
                ('logo_principale', models.ImageField(blank=True, null=True, upload_to=user_auth.models.upload_path_azienda_logo, verbose_name='Logo Principale')),
                ('logo_attestato', models.ImageField(blank=True, null=True, upload_to=user_auth.models.upload_path_azienda_attestato, verbose_name='Logo per Attestati')),
                ('stato_contratto', models.CharField(choices=[('ATTIVO', 'Attivo'), ('SOSPESO', 'Sospeso'), ('SCADUTO', 'Scaduto'), ('IN_ATTIVAZIONE', 'In Attivazione')], default='IN_ATTIVAZIONE', max_length=20, verbose_name='Stato Contratto')),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_scadenza_contratto', models.DateField(blank=True, null=True, verbose_name='Data Scadenza Contratto')),
                ('mod_trattamenti', models.BooleanField(default=False, verbose_name='Abilita Modulo Trattamenti')),
                ('mod_documenti', models.BooleanField(default=False, verbose_name='Abilita Modulo Documenti')),
                ('mod_audit', models.BooleanField(default=False, verbose_name='Abilita Modulo Audit')),
                ('mod_videosorveglianza', models.BooleanField(default=False, verbose_name='Abilita Modulo Videosorveglianza')),
                ('mod_tia', models.BooleanField(default=False, verbose_name='Abilita Modulo TIA Estero')),
                ('mod_organigramma', models.BooleanField(default=False, verbose_name='Abilita Modulo Organigramma')),
                ('note_admin', models.TextField(blank=True, null=True, verbose_name='Note Interne Admin')),
            ],
            options={
                'verbose_name_plural': 'Aziende',
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Prodotti di Servizio',
            },
        ),
        migrations.CreateModel(
            name='NotaAzienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='user_auth.azienda')),
                ('creata_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Note Aziendali (Interne)',
            },
        ),
        migrations.CreateModel(
            name='Consulente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('aziende_gestite', models.ManyToManyField(blank=True, related_name='consulenti', to='user_auth.azienda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo_consulente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profili Consulente',
            },
        ),
        migrations.CreateModel(
            name='AdminReferente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodotti', models.ManyToManyField(blank=True, related_name='referenti_admin', to='user_auth.prodotto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo_admin_referente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Referenti Interni (Prodotti)',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='azienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utenti', to='user_auth.azienda', verbose_name='Azienda'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
