# Generated by Django 4.2.26 on 2025-11-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='mod_csirt',
            field=models.BooleanField(default=False, verbose_name='Abilita Modulo Referente CSIRT (NIS2)'),
        ),
    ]
