# Generated by Django 4.2.26 on 2025-11-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_azienda_mod_csirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azienda',
            name='mod_csirt',
        ),
    ]
