# Generated by Django 4.2.26 on 2025-11-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_azienda_mod_csirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='mod_csirt',
            field=models.BooleanField(default=False, verbose_name='Abilita Modulo Referente CSIRT (NIS2)'),
        ),
    ]
