# Generated by Django 4.2.26 on 2025-12-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_azienda_mod_csirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='mod_cruscotto',
            field=models.BooleanField(default=True, verbose_name='Visualizzazione Cruscotto Principale'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='mod_formazione',
            field=models.BooleanField(default=True, verbose_name='Gestione Formazione'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='mod_incidenti',
            field=models.BooleanField(default=True, verbose_name='Segnalazione Incidenti'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='mod_richieste',
            field=models.BooleanField(default=True, verbose_name='Richieste Interessati'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='mod_storico_audit',
            field=models.BooleanField(default=True, verbose_name='Storico Sessioni Audit'),
        ),
    ]
