# Generated by Django 4.2.26 on 2025-12-01 18:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_azienda_mod_cruscotto_azienda_mod_formazione_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminreferente',
            options={'verbose_name': 'Admin Referente'},
        ),
        migrations.AlterModelOptions(
            name='consulente',
            options={'verbose_name': 'Consulente', 'verbose_name_plural': 'Consulenti'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
        migrations.AlterModelOptions(
            name='notaazienda',
            options={'verbose_name': 'Nota Aziendale'},
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'verbose_name': 'Prodotto', 'verbose_name_plural': 'Prodotti'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='adminreferente',
            name='prodotti',
        ),
        migrations.RemoveField(
            model_name='azienda',
            name='data_scadenza_contratto',
        ),
        migrations.RemoveField(
            model_name='azienda',
            name='note_admin',
        ),
        migrations.RemoveField(
            model_name='azienda',
            name='partita_iva',
        ),
        migrations.RemoveField(
            model_name='azienda',
            name='stato_contratto',
        ),
        migrations.RemoveField(
            model_name='consulente',
            name='aziende_gestite',
        ),
        migrations.RemoveField(
            model_name='consulente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='consulente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='notaazienda',
            name='creata_da',
        ),
        migrations.AddField(
            model_name='azienda',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='azienda',
            name='manager_users',
            field=models.ManyToManyField(blank=True, related_name='aziende_gestite_direttamente', to=settings.AUTH_USER_MODEL, verbose_name='Manager (Utenti Consulenti)'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='p_iva',
            field=models.CharField(default='', max_length=20, verbose_name='P.IVA/Cod. Fisc.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulente',
            name='codice_albo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codice Albo Professionale'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_nascita',
            field=models.DateField(blank=True, null=True, verbose_name='Data di Nascita'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_dpo',
            field=models.BooleanField(default=False, verbose_name='Designato come DPO'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione',
            field=models.TextField(blank=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='adminreferente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='logo_attestato',
            field=models.ImageField(blank=True, null=True, upload_to=user_auth.models.upload_path_azienda_attestato, verbose_name='Logo Attestato'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_audit',
            field=models.BooleanField(default=True, verbose_name='Attiva Audit Compliance'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_cruscotto',
            field=models.BooleanField(default=True, verbose_name='Attiva Cruscotto principale'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_csirt',
            field=models.BooleanField(default=False, verbose_name='Attiva Gestione CSIRT (NIS2)'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_documenti',
            field=models.BooleanField(default=True, verbose_name='Attiva Gestione Documenti'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_formazione',
            field=models.BooleanField(default=True, verbose_name='Attiva Gestione Formazione'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_incidenti',
            field=models.BooleanField(default=True, verbose_name='Attiva Segnalazione Incidenti'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_organigramma',
            field=models.BooleanField(default=False, verbose_name='Attiva Organigramma Privacy'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_richieste',
            field=models.BooleanField(default=True, verbose_name='Attiva Richieste Interessati'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_storico_audit',
            field=models.BooleanField(default=True, verbose_name='Attiva Storico Sessioni Audit'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_tia',
            field=models.BooleanField(default=False, verbose_name='Attiva TIA Estero'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_trattamenti',
            field=models.BooleanField(default=True, verbose_name='Attiva Registro Trattamenti'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_videosorveglianza',
            field=models.BooleanField(default=False, verbose_name='Attiva Videosorveglianza'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Azienda'),
        ),
        migrations.AlterField(
            model_name='consulente',
            name='user',
            field=models.OneToOneField(limit_choices_to={'ruolo': 'CONSULENTE'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='azienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utenti_aziendali', to='user_auth.azienda', verbose_name='Azienda Associata'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ruolo',
            field=models.CharField(choices=[('ADMIN', 'Amministratore di Sistema'), ('CONSULENTE', 'Consulente / DPO Esterno'), ('REFERENTE', 'Referente Privacy Aziendale'), ('STUDENTE', 'Dipendente / Utente E-learning')], default='STUDENTE', max_length=20, verbose_name='Ruolo Utente'),
        ),
        migrations.AlterField(
            model_name='notaazienda',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome Prodotto'),
        ),
    ]
