# Generated by Django 4.2.26 on 2025-12-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_adminreferente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminreferente',
            options={'verbose_name': 'Referente ADMIN', 'verbose_name_plural': 'Referenti ADMIN'},
        ),
        migrations.AlterModelOptions(
            name='notaazienda',
            options={'verbose_name': 'Nota Aziendale', 'verbose_name_plural': 'Note Aziendali'},
        ),
        migrations.AddField(
            model_name='azienda',
            name='can_mod_audit',
            field=models.BooleanField(default=True, verbose_name='Admin: Permetti Audit Compliance'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='can_mod_csirt',
            field=models.BooleanField(default=True, verbose_name='Admin: Permetti Gestione CSIRT (NIS2)'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='can_mod_documenti',
            field=models.BooleanField(default=True, verbose_name='Admin: Permetti Gestione Documentale'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='can_mod_formazione',
            field=models.BooleanField(default=True, verbose_name='Admin: Permetti Gestione Formazione'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='can_mod_incidenti',
            field=models.BooleanField(default=True, verbose_name='Admin: Permetti Segnalazione Incidenti'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='can_mod_organigramma',
            field=models.BooleanField(default=True, verbose_name='Admin: Permetti Organigramma Privacy'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='can_mod_richieste',
            field=models.BooleanField(default=True, verbose_name='Admin: Permetti Richieste Interessati'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='can_mod_tia',
            field=models.BooleanField(default=True, verbose_name='Admin: Permetti TIA Estero'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='can_mod_trattamenti',
            field=models.BooleanField(default=True, verbose_name='Admin: Permetti Registro Trattamenti'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='can_mod_videosorveglianza',
            field=models.BooleanField(default=True, verbose_name='Admin: Permetti Videosorveglianza'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_audit',
            field=models.BooleanField(default=False, verbose_name='Attiva Audit Compliance'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_documenti',
            field=models.BooleanField(default=False, verbose_name='Attiva Gestione Documenti'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_formazione',
            field=models.BooleanField(default=False, verbose_name='Attiva Gestione Formazione'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_incidenti',
            field=models.BooleanField(default=False, verbose_name='Attiva Segnalazione Incidenti'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_richieste',
            field=models.BooleanField(default=False, verbose_name='Attiva Richieste Interessati'),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='mod_trattamenti',
            field=models.BooleanField(default=False, verbose_name='Attiva Registro Trattamenti'),
        ),
    ]
