# Generated by Django 4.2.25 on 2026-01-16 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_adminreferente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.CharField(choices=[('LOGIN', 'Accesso'), ('LOGOUT', 'Uscita'), ('CREATE', 'Creazione'), ('UPDATE', 'Modifica'), ('DELETE', 'Eliminazione'), ('VIEW', 'Visualizzazione')], max_length=20)),
                ('modello', models.CharField(blank=True, max_length=100, null=True)),
                ('descrizione', models.TextField()),
                ('indirizzo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log di Audit',
                'verbose_name_plural': 'Log di Audit',
                'ordering': ['-data_ora'],
            },
        ),
    ]
