# Generated by Django 4.2.26 on 2025-11-23 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome Categoria')),
                ('domande_totali', models.PositiveIntegerField(default=0, verbose_name='N. Domande (Obsoleto)')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name_plural': 'Cruscotto: Categorie Audit (Admin)',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='AuditDomanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(verbose_name='Testo della Domanda')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domande', to='compliance.auditcategoria')),
            ],
            options={
                'verbose_name_plural': 'Cruscotto: Domande Audit (Admin)',
                'ordering': ['categoria__ordine', 'ordine'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaDati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Categoria Dati')),
                ('is_speciale', models.BooleanField(default=False, verbose_name='Dato Particolare (Art. 9)')),
            ],
            options={
                'verbose_name_plural': 'Wizard (P2): Categorie Dati',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Doc: Categorie (Admin)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Destinatario/Fornitore')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Servizio Fornito')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatari', to='user_auth.azienda', verbose_name='Azienda Proprietaria')),
            ],
            options={
                'verbose_name_plural': 'Wizard (P2): Destinatari/Fornitori',
                'ordering': ['azienda', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAziendale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Documento')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='user_auth.azienda')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compliance.categoriadocumento')),
            ],
            options={
                'verbose_name_plural': 'Documenti Aziendali',
                'ordering': ['azienda', 'categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DomandaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(verbose_name='Testo della Domanda')),
                ('punteggio_rischio', models.IntegerField(default=5, verbose_name="Punteggio Rischio (se 'Sì')")),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name_plural': 'Checklist Rischio (Domande Admin)',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='Paese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('gruppo_tia', models.CharField(choices=[('SEE', 'Area SEE (UE + NO/IS/LI) - Verde'), ('ADEGUATO', 'Adeguato (White List) - Verde'), ('USA', 'USA (Data Privacy Framework) - Check'), ('RISCHIO_ALTO', 'Rischio Alto (Black List) - Rosso'), ('RESTO_MONDO', 'Resto del Mondo - Giallo/Standard')], default='RESTO_MONDO', help_text='Classificazione del Paese per il calcolo del rischio.', max_length=20, verbose_name='Gruppo TIA')),
            ],
            options={
                'verbose_name_plural': 'TIA: Database Paesi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SoggettoInteressato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Soggetto Interessato')),
            ],
            options={
                'verbose_name_plural': 'Wizard (P2): Soggetti Interessati',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Videosorveglianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_impianto', models.CharField(default='Impianto Principale', max_length=255, verbose_name='Nome Impianto')),
                ('data_compilazione', models.DateField(auto_now_add=True)),
                ('presenza_dipendenti', models.BooleanField(default=False, verbose_name='Ci sono dipendenti nelle aree riprese?')),
                ('scopo', models.CharField(default='Sicurezza Patrimonio', max_length=100, verbose_name='Finalità Principale')),
                ('accordo_sindacale', models.BooleanField(default=False, verbose_name='Accordo Sindacale firmato?')),
                ('autorizzazione_itl', models.BooleanField(default=False, verbose_name='Autorizzazione ITL ottenuta?')),
                ('riprende_suolo_pubblico', models.BooleanField(default=False, verbose_name='Riprende suolo pubblico (strada)?')),
                ('telecamere_intelligenti', models.BooleanField(default=False, verbose_name='Smart Cam (Facciale/Targhe)?')),
                ('numero_telecamere', models.PositiveIntegerField(default=1, verbose_name='Numero Telecamere')),
                ('tempo_conservazione', models.CharField(choices=[('24H', '24 Ore (Standard)'), ('72H', '72 Ore (Weekend/Ponti)'), ('7G', '7 Giorni (Banche/Gioiellerie)'), ('OLTRE', 'Oltre (Richiede verifica)')], default='24H', max_length=10)),
                ('angoli_visuale_ok', models.BooleanField(default=False, verbose_name='Angoli visuale verificati? (No bagni/scrivanie)')),
                ('cartelli_posizionati', models.BooleanField(default=False, verbose_name='Cartelli (I Livello) posizionati?')),
                ('informativa_completa', models.BooleanField(default=False, verbose_name='Informativa Estesa disponibile?')),
                ('nomine_interne', models.BooleanField(default=False, verbose_name='Nomine Incaricati alla visione effettuate?')),
                ('nomine_esterne', models.BooleanField(default=False, verbose_name='Nomina Manutentore/Vigilanza (Resp. Esterno)?')),
                ('stato_conformita', models.CharField(default='IN_VALUTAZIONE', max_length=20)),
                ('azioni_richieste', models.TextField(blank=True, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videosorveglianza', to='user_auth.azienda')),
                ('compilato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impianto Videosorveglianza',
                'verbose_name_plural': 'Videosorveglianza',
            },
        ),
        migrations.CreateModel(
            name='VersioneDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documenti_aziende/')),
                ('note_versione', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note sulla versione')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('caricato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versioni', to='compliance.documentoaziendale')),
            ],
            options={
                'verbose_name_plural': 'Versioni Documento',
                'ordering': ['-data_caricamento'],
            },
        ),
        migrations.CreateModel(
            name='ValutazioneTIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_valutazione', models.DateField(auto_now_add=True)),
                ('fornitore', models.CharField(max_length=200, verbose_name='Nome Fornitore')),
                ('descrizione_dati', models.TextField(verbose_name='Tipologia Dati')),
                ('usa_framework', models.BooleanField(default=False, help_text='Solo per USA: Il fornitore è nella lista del Data Privacy Framework?', verbose_name='Certificato DPF?')),
                ('crittografia_transito', models.BooleanField(default=False, verbose_name='Crittografia in Transito (HTTPS)')),
                ('crittografia_riposo', models.BooleanField(default=False, verbose_name='Crittografia a Riposo')),
                ('gestione_chiavi', models.CharField(choices=[('NOI', 'Esportatore (Noi/UE)'), ('FORNITORE', 'Importatore (Fornitore Extra-UE)'), ('CONDIVISE', 'Condivise/Non chiaro')], default='FORNITORE', max_length=15, verbose_name='Chi ha le chiavi?')),
                ('pseudonimizzazione', models.BooleanField(default=False, verbose_name='Pseudonimizzazione')),
                ('esito_calcolato', models.CharField(choices=[('VERDE', 'Sicuro'), ('GIALLO', 'A Rischio (Misure Suppl.)'), ('ROSSO', 'Bloccato')], default='ROSSO', max_length=10)),
                ('note_finali', models.TextField(blank=True, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tias', to='user_auth.azienda')),
                ('compilato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paese_destinazione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compliance.paese', verbose_name='Paese di Destinazione')),
            ],
            options={
                'verbose_name_plural': 'Valutazioni TIA',
            },
        ),
        migrations.CreateModel(
            name='Trattamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ruolo', models.CharField(choices=[('TITOLARE', 'Titolare'), ('RESPONSABILE', 'Responsabile')], default='TITOLARE', max_length=15, verbose_name="Ruolo dell'Azienda")),
                ('per_conto_di', models.CharField(blank=True, max_length=255, null=True, verbose_name='Per conto di (Cliente/Titolare)')),
                ('nome_trattamento', models.CharField(max_length=255, verbose_name='Nome Trattamento')),
                ('finalita', models.TextField(verbose_name='Finalità del trattamento')),
                ('destinatari_interni', models.TextField(blank=True, null=True, verbose_name='Destinatari Interni')),
                ('tempo_conservazione', models.CharField(max_length=255, verbose_name='Tempo di Conservazione')),
                ('misure_sicurezza', models.TextField(blank=True, null=True, verbose_name='Misure di Sicurezza Applicate')),
                ('livello_rischio', models.CharField(choices=[('BASSO', 'Basso'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('NON_CALCOLATO', 'Non Calcolato')], default='NON_CALCOLATO', max_length=15, verbose_name='Livello Rischio Calcolato')),
                ('dpia_necessaria', models.BooleanField(default=False, verbose_name='DPIA Necessaria')),
                ('punteggio_rischio_calcolato', models.IntegerField(default=0, verbose_name='Punteggio Rischio (Calcolato)')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trattamenti', to='user_auth.azienda', verbose_name='Azienda')),
                ('categorie_dati', models.ManyToManyField(to='compliance.categoriadati', verbose_name='Categorie di Dati Trattati')),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Compilato da')),
                ('destinatari_esterni', models.ManyToManyField(blank=True, to='compliance.destinatario', verbose_name='Destinatari Esterni (Fornitori)')),
                ('soggetti_interessati', models.ManyToManyField(to='compliance.soggettointeressato', verbose_name='Soggetti Interessati')),
            ],
            options={
                'verbose_name_plural': 'Registro Trattamenti (P2)',
                'ordering': ['azienda', 'nome_trattamento'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='templates_documenti/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.categoriadocumento')),
            ],
            options={
                'verbose_name_plural': 'Doc: Template (Admin)',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_software', models.CharField(max_length=100, verbose_name='Nome Software')),
                ('scopo_utilizzo', models.CharField(max_length=200, verbose_name='Scopo')),
                ('tipologia', models.CharField(choices=[('LOCALE', 'Installato su PC'), ('CLOUD', 'Cloud / SaaS'), ('SERVER', 'On-Premise Server')], default='CLOUD', max_length=20)),
                ('locazione_server', models.CharField(blank=True, max_length=100, null=True, verbose_name='Locazione Dati')),
                ('amministratore', models.CharField(blank=True, max_length=100, null=True, verbose_name='Admin')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='user_auth.azienda')),
            ],
            options={
                'verbose_name_plural': 'Inventario Software',
            },
        ),
        migrations.CreateModel(
            name='RuoloPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cognome', models.CharField(max_length=100, verbose_name='Nome e Cognome / Ragione Sociale')),
                ('ruolo_tipo', models.CharField(choices=[('DPO', 'DPO / RPD (Controllo)'), ('REFERENTE', 'Referente/Capo Reparto (Gestionale)'), ('ADS', 'Amministratore di Sistema (IT Security)'), ('AUTORIZZATO', 'Autorizzati / Incaricati (Operativo)'), ('ESTERNO', 'Responsabile Esterno (Fornitore)')], max_length=20, verbose_name='Livello Ruolo')),
                ('dettaglio_ruolo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Etichetta Ruolo')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organigramma', to='user_auth.azienda')),
            ],
            options={
                'verbose_name_plural': 'Organigramma Privacy',
                'ordering': ['ruolo_tipo', 'nome_cognome'],
            },
        ),
        migrations.CreateModel(
            name='RichiestaInteressato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ricezione', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Ricezione')),
                ('data_scadenza_risposta', models.DateTimeField(blank=True, null=True, verbose_name='Scadenza 30 Giorni')),
                ('tipo_richiesta', models.CharField(choices=[('ACCESSO', 'Accesso'), ('RETTIFICA', 'Rettifica'), ('CANCELLAZIONE', 'Cancellazione'), ('LIMITAZIONE', 'Limitazione'), ('PORTABILITA', 'Portabilità'), ('OPPOSIZIONE', 'Opposizione'), ('ALTRO', 'Altro')], max_length=15)),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('IN_LAVORAZIONE', 'In Lavorazione'), ('EVASA', 'Evasa'), ('RESPINTA', 'Respinta')], default='APERTA', max_length=15)),
                ('richiedente_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('richiedente_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('richiesta_testo', models.TextField(verbose_name='Testo')),
                ('note_interne', models.TextField(blank=True, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste', to='user_auth.azienda')),
                ('gestita_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Richieste Interessati (Ticket)',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rilevamento', models.DateTimeField(verbose_name='Data Rilevamento')),
                ('data_scadenza_notifica', models.DateTimeField(blank=True, null=True, verbose_name='Scadenza 72 Ore')),
                ('titolo', models.CharField(max_length=255, verbose_name='Titolo Incidente')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('stato', models.CharField(choices=[('APERTO', 'Aperto'), ('IN_GESTIONE', 'In Gestione'), ('NOTIFICATO', 'Notificato'), ('CHIUSO', 'Chiuso')], default='APERTO', max_length=20)),
                ('valutazione_rischio', models.TextField(blank=True, null=True, verbose_name='Valutazione Rischio')),
                ('notifica_garante_necessaria', models.BooleanField(default=False)),
                ('notifica_interessati_necessaria', models.BooleanField(default=False)),
                ('azioni_correttive', models.TextField(blank=True, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidenti', to='user_auth.azienda')),
                ('segnalato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Incidenti (Data Breach)',
            },
        ),
        migrations.AddField(
            model_name='documentoaziendale',
            name='creato_da_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.templatedocumento', verbose_name='Creato da Template'),
        ),
        migrations.CreateModel(
            name='Compito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, verbose_name='Compito Globale')),
                ('titolo', models.CharField(max_length=255, verbose_name='Titolo Compito')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('stato', models.CharField(choices=[('APERTO', 'Aperto'), ('COMPLETATO', 'Completato')], default='APERTO', max_length=15)),
                ('priorita', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BASSA', 'Bassa')], default='MEDIA', max_length=15)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_scadenza', models.DateField(blank=True, null=True, verbose_name='Data Scadenza')),
                ('notifica_scadenza_inviata', models.BooleanField(default=False, verbose_name='Notifica Inviata')),
                ('aziende_assegnate', models.ManyToManyField(blank=True, related_name='compiti', to='user_auth.azienda', verbose_name='Aziende Specifiche')),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assegnato da')),
            ],
            options={
                'verbose_name_plural': 'Compiti e Scadenze',
                'ordering': ['stato', 'data_scadenza'],
            },
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Audit')),
                ('note', models.TextField(blank=True, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_sessions', to='user_auth.azienda')),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sessioni Audit (Storico)',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_inventario', models.CharField(max_length=50, verbose_name='ID Asset')),
                ('tipo_asset', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('SERVER', 'Server'), ('SMARTPHONE', 'Smartphone'), ('TABLET', 'Tablet'), ('HDD_EST', 'Hard Disk Esterno'), ('NAS', 'NAS'), ('ALTRO', 'Altro')], max_length=20)),
                ('marca_modello', models.CharField(max_length=100, verbose_name='Marca e Modello')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number')),
                ('hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome di Rete')),
                ('utente_assegnatario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Utente Assegnatario')),
                ('reparto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reparto')),
                ('luogo_fisico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Luogo Fisico')),
                ('tratta_dati_personali', models.BooleanField(default=False, verbose_name='Tratta Dati?')),
                ('categoria_dati', models.CharField(choices=[('NESSUNO', 'Nessuno'), ('COMUNI', 'Dati Comuni'), ('SENSIBILI', 'Dati Sensibili/Sanitari'), ('GIUDIZIARI', 'Dati Giudiziari')], default='NESSUNO', max_length=20)),
                ('criticita', models.CharField(choices=[('BASSA', 'Bassa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('disco_crittografato', models.BooleanField(default=False, verbose_name='Crittografato')),
                ('antivirus_installato', models.BooleanField(default=False, verbose_name='Antivirus')),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True, verbose_name='OS')),
                ('stato', models.CharField(choices=[('ATTIVO', 'Attivo'), ('RIPARAZIONE', 'In Riparazione'), ('MAGAZZINO', 'In Magazzino'), ('DISMESSO', 'Dismesso/Venduto'), ('RUBATO', 'Rubato')], default='ATTIVO', max_length=20)),
                ('data_acquisto', models.DateField(blank=True, null=True)),
                ('data_scadenza_garanzia', models.DateField(blank=True, null=True)),
                ('wiping_effettuato', models.BooleanField(default=False, verbose_name='Wiping')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='user_auth.azienda')),
            ],
            options={
                'verbose_name_plural': 'Registro Asset (Hardware)',
            },
        ),
        migrations.CreateModel(
            name='RispostaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risposta', models.BooleanField(default=False, verbose_name='Risposta (Sì/No)')),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.domandachecklist')),
                ('trattamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte_checklist', to='compliance.trattamento')),
            ],
            options={
                'verbose_name_plural': 'Checklist Rischio (Risposte Utenti)',
                'unique_together': {('trattamento', 'domanda')},
            },
        ),
        migrations.CreateModel(
            name='AuditRisposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risposta', models.CharField(choices=[('Sì', 'Sì'), ('No', 'No')], default='No', max_length=3)),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.auditdomanda')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to='compliance.auditsession')),
            ],
            options={
                'verbose_name_plural': 'Cruscotto: Risposte Audit',
                'unique_together': {('sessione', 'domanda')},
            },
        ),
    ]
