# Generated by Django 4.2.26 on 2025-11-27 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0001_initial'),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenteCSIRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nomina', models.DateField(default=django.utils.timezone.now, verbose_name='Data Nomina')),
                ('ruolo_aziendale', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruolo Aziendale')),
                ('sostituti_dettagli', models.TextField(blank=True, null=True, verbose_name='Dettagli Sostituti (Nome, Contatti)')),
                ('competenze_documentate', models.BooleanField(default=False, verbose_name='Competenza documentata (Art. 5)')),
                ('motivo_esterno', models.TextField(blank=True, null=True, verbose_name='Motivazione Scelta Esterna')),
                ('azienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referente_csirt', to='user_auth.azienda', verbose_name='Azienda')),
                ('referente_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csirt_principal', to=settings.AUTH_USER_MODEL, verbose_name='Referente Principale')),
            ],
            options={
                'verbose_name': 'Referente CSIRT (NIS2)',
                'verbose_name_plural': 'Gestione Referente CSIRT (NIS2)',
            },
        ),
        migrations.CreateModel(
            name='NotificaIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_incidente', models.CharField(max_length=255, verbose_name='Titolo Incidente NIS2')),
                ('data_incidente', models.DateTimeField(verbose_name='Data e Ora Incidente')),
                ('data_notifica', models.DateTimeField(blank=True, null=True, verbose_name='Data Notifica ACN')),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('NOTIFICATA', 'Notificata ACN'), ('CHIUSA', 'Chiusa')], default='APERTA', max_length=20, verbose_name='Stato Notifica')),
                ('descrizione_danno', models.TextField(verbose_name='Descrizione Danno/Impatto')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_incidenti', to='user_auth.azienda')),
                ('referente_csirt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.referentecsirt', verbose_name='Referente che ha notificato')),
            ],
            options={
                'verbose_name': 'Notifica Incidente NIS2',
                'verbose_name_plural': 'Registro Notifiche NIS2',
            },
        ),
    ]
