# Generated by Django 4.2.26 on 2025-11-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_azienda_mod_csirt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0002_referentecsirt_notificaincidente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='auditcategoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='auditdomanda',
            options={},
        ),
        migrations.AlterModelOptions(
            name='auditrisposta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='auditsession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoriadati',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoriadocumento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='compito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentoaziendale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='domandachecklist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='incidente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paese',
            options={},
        ),
        migrations.AlterModelOptions(
            name='richiestainteressato',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rispostachecklist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ruoloprivacy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={},
        ),
        migrations.AlterModelOptions(
            name='soggettointeressato',
            options={},
        ),
        migrations.AlterModelOptions(
            name='templatedocumento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trattamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='valutazionetia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='versionedocumento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='videosorveglianza',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='rispostachecklist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='data_acquisto',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='data_scadenza_garanzia',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='sistema_operativo',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='wiping_effettuato',
        ),
        migrations.RemoveField(
            model_name='auditcategoria',
            name='domande_totali',
        ),
        migrations.RemoveField(
            model_name='categoriadati',
            name='is_speciale',
        ),
        migrations.RemoveField(
            model_name='compito',
            name='data_creazione',
        ),
        migrations.RemoveField(
            model_name='compito',
            name='notifica_scadenza_inviata',
        ),
        migrations.RemoveField(
            model_name='referentecsirt',
            name='ruolo_aziendale',
        ),
        migrations.RemoveField(
            model_name='referentecsirt',
            name='sostituti_dettagli',
        ),
        migrations.RemoveField(
            model_name='ruoloprivacy',
            name='dettaglio_ruolo',
        ),
        migrations.RemoveField(
            model_name='trattamento',
            name='data_creazione',
        ),
        migrations.RemoveField(
            model_name='trattamento',
            name='data_ultima_modifica',
        ),
        migrations.RemoveField(
            model_name='valutazionetia',
            name='crittografia_riposo',
        ),
        migrations.RemoveField(
            model_name='valutazionetia',
            name='crittografia_transito',
        ),
        migrations.RemoveField(
            model_name='valutazionetia',
            name='gestione_chiavi',
        ),
        migrations.RemoveField(
            model_name='valutazionetia',
            name='note_finali',
        ),
        migrations.RemoveField(
            model_name='valutazionetia',
            name='pseudonimizzazione',
        ),
        migrations.RemoveField(
            model_name='valutazionetia',
            name='usa_framework',
        ),
        migrations.RemoveField(
            model_name='videosorveglianza',
            name='angoli_visuale_ok',
        ),
        migrations.RemoveField(
            model_name='videosorveglianza',
            name='cartelli_posizionati',
        ),
        migrations.RemoveField(
            model_name='videosorveglianza',
            name='informativa_completa',
        ),
        migrations.RemoveField(
            model_name='videosorveglianza',
            name='nomine_esterne',
        ),
        migrations.RemoveField(
            model_name='videosorveglianza',
            name='nomine_interne',
        ),
        migrations.RemoveField(
            model_name='videosorveglianza',
            name='presenza_dipendenti',
        ),
        migrations.RemoveField(
            model_name='videosorveglianza',
            name='riprende_suolo_pubblico',
        ),
        migrations.RemoveField(
            model_name='videosorveglianza',
            name='telecamere_intelligenti',
        ),
        migrations.AddField(
            model_name='auditrisposta',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditsession',
            name='completato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paese',
            name='adeguatezza_ue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='codice_ipa',
            field=models.CharField(blank=True, help_text='Solo per Pubbliche Amministrazioni', max_length=100, null=True, verbose_name='Codice IPA'),
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='pc_cognome',
            field=models.CharField(default='', max_length=100, verbose_name='Cognome Punto di Contatto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='pc_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Punto di Contatto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='pc_nome',
            field=models.CharField(default='', help_text='Chi effettua la designazione', max_length=100, verbose_name='Nome Punto di Contatto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='ref_cf',
            field=models.CharField(default='', max_length=16, verbose_name='Codice Fiscale Referente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='ref_cognome',
            field=models.CharField(default='', max_length=100, verbose_name='Cognome Referente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='ref_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Referente (Istituzionale)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='ref_nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome Referente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='ref_ruolo',
            field=models.CharField(default='', help_text='Es. CISO, IT Manager, Consulente Esterno', max_length=100, verbose_name='Ruolo Aziendale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='ref_telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Telefono Reperibilità (H24)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='sos1_cf',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CF Sostituto 1'),
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='sos1_cognome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognome Sostituto 1'),
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='sos1_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Sostituto 1'),
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='sos1_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Sostituto 1'),
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='sos2_cf',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CF Sostituto 2'),
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='sos2_cognome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognome Sostituto 2'),
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='sos2_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Sostituto 2'),
        ),
        migrations.AddField(
            model_name='referentecsirt',
            name='sos2_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Sostituto 2'),
        ),
        migrations.AddField(
            model_name='ruoloprivacy',
            name='atto_nomina',
            field=models.FileField(blank=True, null=True, upload_to='nomine/'),
        ),
        migrations.AddField(
            model_name='ruoloprivacy',
            name='contatti',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='software',
            name='fornitore',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='valutazionetia',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='videosorveglianza',
            name='cartelli_esposti',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videosorveglianza',
            name='dvr_conforme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videosorveglianza',
            name='registrazione_attiva',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='antivirus_installato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='categoria_dati',
            field=models.CharField(choices=[('COMUNI', 'Comuni'), ('PARTICOLARI', 'Particolari'), ('GIUDIZIARI', 'Giudiziari')], default='COMUNI', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='codice_inventario',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='criticita',
            field=models.CharField(choices=[('BASSA', 'Bassa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='disco_crittografato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='luogo_fisico',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='marca_modello',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='reparto',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='stato',
            field=models.CharField(choices=[('IN_USO', 'In Uso'), ('DISMESSO', 'Dismesso'), ('MANUTENZIONE', 'In Manutenzione')], default='IN_USO', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tipo_asset',
            field=models.CharField(choices=[('PC', 'PC/Laptop'), ('SERVER', 'Server'), ('MOBILE', 'Smartphone/Tablet'), ('ALTRO', 'Altro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tratta_dati_personali',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='utente_assegnatario',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditcategoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditcategoria',
            name='ordine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditdomanda',
            name='ordine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditdomanda',
            name='testo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditrisposta',
            name='risposta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='note',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriadati',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoriadocumento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compito',
            name='aziende_assegnate',
            field=models.ManyToManyField(blank=True, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='compito',
            name='creato_da',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='compiti_creati', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compito',
            name='data_scadenza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compito',
            name='descrizione',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compito',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compito',
            name='priorita',
            field=models.CharField(choices=[('BASSA', 'Bassa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='compito',
            name='stato',
            field=models.CharField(choices=[('APERTO', 'Aperto'), ('IN_CORSO', 'In Corso'), ('COMPLETATO', 'Completato')], default='APERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='compito',
            name='titolo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='documentoaziendale',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='documentoaziendale',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.categoriadocumento'),
        ),
        migrations.AlterField(
            model_name='documentoaziendale',
            name='creato_da_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.templatedocumento'),
        ),
        migrations.AlterField(
            model_name='documentoaziendale',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='domandachecklist',
            name='ordine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='domandachecklist',
            name='punteggio_rischio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='domandachecklist',
            name='testo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='azioni_correttive',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidente',
            name='data_rilevamento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='data_scadenza_notifica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='descrizione',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='stato',
            field=models.CharField(choices=[('APERTO', 'Aperto'), ('GESTIONE', 'In Gestione'), ('CHIUSO', 'Chiuso')], default='APERTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='titolo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='valutazione_rischio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paese',
            name='gruppo_tia',
            field=models.IntegerField(default=3, help_text='1=Sicuro, 2=Medio, 3=Rischio'),
        ),
        migrations.AlterField(
            model_name='paese',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='competenze_documentate',
            field=models.BooleanField(default=False, verbose_name='Competenza documentata'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='referente_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csirt_principal', to=settings.AUTH_USER_MODEL, verbose_name='Utente Sistema (Opzionale)'),
        ),
        migrations.AlterField(
            model_name='richiestainteressato',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='richiestainteressato',
            name='data_ricezione',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='richiestainteressato',
            name='data_scadenza_risposta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='richiestainteressato',
            name='gestita_da',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='richiestainteressato',
            name='note_interne',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='richiestainteressato',
            name='richiedente_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='richiestainteressato',
            name='richiedente_nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='richiestainteressato',
            name='richiesta_testo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='richiestainteressato',
            name='stato',
            field=models.CharField(choices=[('RICEVUTA', 'Ricevuta'), ('IN_LAVORAZIONE', 'In Lavorazione'), ('EVASA', 'Evasa'), ('RIFIUTATA', 'Rifiutata')], default='RICEVUTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='richiestainteressato',
            name='tipo_richiesta',
            field=models.CharField(choices=[('ACCESSO', 'Accesso'), ('RETTIFICA', 'Rettifica'), ('CANCELLAZIONE', 'Cancellazione'), ('OPPOSIZIONE', 'Opposizione'), ('PORTABILITA', 'Portabilità')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rispostachecklist',
            name='risposta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruoloprivacy',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='ruoloprivacy',
            name='nome_cognome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ruoloprivacy',
            name='ruolo_tipo',
            field=models.CharField(choices=[('DPO', 'DPO'), ('REFERENTE', 'Referente Privacy'), ('ADS', 'Amministratore Sistema'), ('AUTORIZZATO', 'Autorizzato'), ('ESTERNO', 'Resp. Esterno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='software',
            name='amministratore',
            field=models.CharField(blank=True, default='', help_text='Chi gestisce questo software', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='software',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='software',
            name='locazione_server',
            field=models.CharField(blank=True, default='', help_text='Es. Italia, Irlanda, USA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='software',
            name='nome_software',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='scopo_utilizzo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='software',
            name='tipologia',
            field=models.CharField(choices=[('LOCALE', 'Installato Locale'), ('CLOUD', 'SaaS/Cloud'), ('APP', 'App Mobile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='soggettointeressato',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='templatedocumento',
            name='descrizione',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatedocumento',
            name='file',
            field=models.FileField(upload_to='templates_docs/'),
        ),
        migrations.AlterField(
            model_name='templatedocumento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='categorie_dati',
            field=models.ManyToManyField(to='compliance.categoriadati'),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='creato_da',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='trattamento',
            name='destinatari_esterni',
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='destinatari_interni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='dpia_necessaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='finalita',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='livello_rischio',
            field=models.CharField(default='BASSO', max_length=20),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='misure_sicurezza',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='nome_trattamento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='per_conto_di',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='punteggio_rischio_calcolato',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='soggetti_interessati',
            field=models.ManyToManyField(to='compliance.soggettointeressato'),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='tempo_conservazione',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trattamento',
            name='tipo_ruolo',
            field=models.CharField(choices=[('TITOLARE', 'Titolare'), ('RESPONSABILE', 'Responsabile')], default='TITOLARE', max_length=20),
        ),
        migrations.AlterField(
            model_name='valutazionetia',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='valutazionetia',
            name='descrizione_dati',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='valutazionetia',
            name='esito_calcolato',
            field=models.CharField(default='ROSSO', max_length=20),
        ),
        migrations.AlterField(
            model_name='valutazionetia',
            name='fornitore',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='valutazionetia',
            name='paese_destinazione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.paese'),
        ),
        migrations.AlterField(
            model_name='versionedocumento',
            name='file',
            field=models.FileField(upload_to='documenti_aziendali/'),
        ),
        migrations.AlterField(
            model_name='versionedocumento',
            name='note_versione',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='videosorveglianza',
            name='accordo_sindacale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videosorveglianza',
            name='autorizzazione_itl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videosorveglianza',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda'),
        ),
        migrations.AlterField(
            model_name='videosorveglianza',
            name='azioni_richieste',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videosorveglianza',
            name='nome_impianto',
            field=models.CharField(default='Impianto Principale', max_length=100),
        ),
        migrations.AlterField(
            model_name='videosorveglianza',
            name='numero_telecamere',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='videosorveglianza',
            name='scopo',
            field=models.CharField(default='Sicurezza Patrimonio', max_length=200),
        ),
        migrations.AlterField(
            model_name='videosorveglianza',
            name='stato_conformita',
            field=models.CharField(default='NON_CONFORME', max_length=20),
        ),
        migrations.AlterField(
            model_name='videosorveglianza',
            name='tempo_conservazione',
            field=models.CharField(choices=[('24H', '24 Ore'), ('48H', '48 Ore'), ('72H', '72 Ore'), ('7GG', '7 Giorni (Richiede accordo)')], default='24H', max_length=50),
        ),
        migrations.DeleteModel(
            name='Destinatario',
        ),
        migrations.AddField(
            model_name='trattamento',
            name='destinatari_esterni',
            field=models.TextField(blank=True, null=True),
        ),
    ]
