# Generated by Django 4.2.26 on 2025-12-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_azienda_mod_csirt'),
        ('compliance', '0003_alter_asset_options_alter_auditcategoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentecsirt',
            name='pc_cognome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognome Punto di Contatto'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='pc_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Punto di Contatto'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='pc_nome',
            field=models.CharField(blank=True, help_text='Chi effettua la designazione', max_length=100, null=True, verbose_name='Nome Punto di Contatto'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_cf',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Codice Fiscale Referente'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_cognome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognome Referente'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Referente (Istituzionale)'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Referente'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_ruolo',
            field=models.CharField(blank=True, help_text='Es. CISO, IT Manager, Consulente Esterno', max_length=100, null=True, verbose_name='Ruolo Aziendale'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono Reperibilità (H24)'),
        ),
        migrations.CreateModel(
            name='ModuloAziendale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivato_dal_consulente', models.BooleanField(default=False, verbose_name="Attivato per l'Azienda")),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda', verbose_name='Azienda')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduli_aziendali', to='compliance.categoriadocumento', verbose_name='Modulo Compliance')),
            ],
            options={
                'verbose_name': 'Modulo Aziendale Attivo',
                'verbose_name_plural': 'Moduli Aziendali Attivi',
                'unique_together': {('azienda', 'categoria')},
            },
        ),
    ]
