# Generated by Django 4.2.26 on 2025-12-02 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_adminreferente_options_and_more'),
        ('compliance', '0004_alter_referentecsirt_pc_cognome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneRete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_architettura', models.CharField(choices=[('STAR', 'Star'), ('MESH', 'Mesh'), ('HIERARCHICAL', 'Gerarchica'), ('FLAT', 'Piatta')], default='HIERARCHICAL', max_length=50, verbose_name='Tipo di Architettura di Rete')),
                ('segmentazione_rete', models.TextField(blank=True, null=True, verbose_name='Descrizione Segmentazione/VLAN')),
                ('firewall_utilizzato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modello/Nome Firewall')),
                ('sistema_ids_ips', models.BooleanField(default=False, verbose_name='Sistema IDS/IPS Attivo')),
                ('gestione_antivirus_centralizzata', models.BooleanField(default=False, verbose_name='Antivirus Centralizzato')),
                ('gestione_vpn', models.CharField(choices=[('AZIENDA', 'Gestita Internamente'), ('ESTERNA', 'Servizio Esterno'), ('NONE', 'Non Usata')], default='NONE', max_length=50, verbose_name='Gestione Accesso Remoto (VPN)')),
                ('politica_patching', models.CharField(choices=[('AUTOMATICO', 'Automatico'), ('MANUALE', 'Manuale Periodico'), ('ASSENTE', 'Assente/No Policy')], default='MANUALE', max_length=50, verbose_name='Politica di Patch Management')),
                ('azienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configurazione_rete', to='user_auth.azienda', verbose_name='Azienda')),
            ],
            options={
                'verbose_name': 'Configurazione di Rete',
                'verbose_name_plural': 'Configurazioni di Rete',
            },
        ),
        migrations.RenameField(
            model_name='incidente',
            old_name='azioni_correttive',
            new_name='actions_correttive',
        ),
        migrations.DeleteModel(
            name='ModuloAziendale',
        ),
    ]
