# Generated by Django 4.2.26 on 2025-12-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_configurazionerete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidente',
            old_name='actions_correttive',
            new_name='azioni_correttive',
        ),
        migrations.CreateModel(
            name='ComponenteRete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_componente', models.CharField(max_length=100, verbose_name='Nome/Identificativo')),
                ('tipo', models.CharField(choices=[('DEVICE', 'Dispositivo Utente'), ('SERVER', 'Server/Virtual Host'), ('FIREWALL', 'Firewall/Router'), ('PRINTER', 'Stampante/Scanner'), ('HUB', 'Switch/Hub'), ('OTHER', 'Altro Nodo')], default='DEVICE', max_length=50, verbose_name='Tipo Componente')),
                ('descrizione_funzione', models.TextField(blank=True, verbose_name='Funzione e Posizione')),
                ('criticita', models.CharField(choices=[('BASSA', 'Bassa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20, verbose_name='Criticità Sicurezza')),
                ('configurazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenti', to='compliance.configurazionerete', verbose_name='Configurazione Rete Madre')),
            ],
            options={
                'verbose_name': 'Componente di Rete',
                'verbose_name_plural': 'Componenti di Rete',
                'ordering': ['tipo', 'nome_componente'],
            },
        ),
    ]
