# Generated by Django 4.2.26 on 2025-12-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_rename_actions_correttive_incidente_azioni_correttive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruoloprivacy',
            options={'verbose_name': 'Ruolo Privacy', 'verbose_name_plural': 'Ruoli Privacy'},
        ),
        migrations.AddField(
            model_name='componenterete',
            name='indirizzo_ip',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Indirizzo IP/Subnet'),
        ),
        migrations.AlterField(
            model_name='ruoloprivacy',
            name='ruolo_tipo',
            field=models.CharField(choices=[('TITOLARE', 'Titolare del Trattamento'), ('RESPONSABILE_TRATTAMENTO', 'Responsabile del Trattamento'), ('DPO', 'DPO'), ('REFERENTE', 'Referente Privacy'), ('ADS', 'Amministratore Sistema'), ('AUTORIZZATO', 'Autorizzato'), ('ESTERNO', 'Resp. Esterno')], max_length=30, verbose_name='Tipo di Ruolo Privacy'),
        ),
    ]
