# Generated by Django 4.2.26 on 2025-12-03 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0007_alter_ruoloprivacy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaincidente',
            name='azioni_correttive',
            field=models.TextField(blank=True, null=True, verbose_name='Azioni Correttive Adottate'),
        ),
        migrations.AddField(
            model_name='notificaincidente',
            name='valutazione_rischio',
            field=models.TextField(blank=True, null=True, verbose_name='Valutazione Rischio e Danno'),
        ),
        migrations.CreateModel(
            name='AllegatoNotifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csirt_allegati/', verbose_name='File Allegato')),
                ('descrizione', models.CharField(blank=True, max_length=255, verbose_name='Descrizione')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('caricato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('notifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='compliance.notificaincidente', verbose_name='Notifica Incidente')),
            ],
            options={
                'verbose_name': 'Allegato Notifica',
                'verbose_name_plural': 'Allegati Notifiche',
            },
        ),
    ]
