# Generated by Django 4.2.26 on 2025-12-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_notificaincidente_azioni_correttive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaincidente',
            name='categoria_incidente',
            field=models.CharField(choices=[('RANSOMWARE', 'Ransomware'), ('DDOS', 'Attacco DDOS'), ('PHISHING', 'Phishing/Spear-Phishing'), ('ACCESS_VIOLATION', 'Violazione di Accesso / Compromissione Account'), ('MALWARE', 'Malware (Generico)')], default='MALWARE', max_length=50, verbose_name='Categoria Incidente (Tassonomia ACN)'),
        ),
        migrations.AddField(
            model_name='notificaincidente',
            name='impatto_stimato',
            field=models.CharField(choices=[('CRITICO', 'Critico (Interruzione Totale)'), ('ALTO', 'Alto (Servizi Essenziali Impattati)'), ('MEDIO', 'Medio (Impatto su Servizi Secondari)'), ('BASSO', 'Basso (Danno Minimo)')], default='ALTO', max_length=20, verbose_name='Impatto stimato (Operativo/Finanziario)'),
        ),
        migrations.AddField(
            model_name='notificaincidente',
            name='playbook_associato',
            field=models.CharField(blank=True, choices=[('RANSOMWARE_P', 'Playbook Ransomware'), ('DDOS_P', 'Playbook DDOS'), ('PHISHING_P', 'Playbook Phishing'), ('GENERIC_P', 'Playbook Generico')], max_length=50, null=True, verbose_name='Playbook di Risposta'),
        ),
        migrations.AddField(
            model_name='notificaincidente',
            name='severita_incidente',
            field=models.CharField(choices=[('CRITICO', 'Critico (Interruzione Totale)'), ('ALTO', 'Alto (Servizi Essenziali Impattati)'), ('MEDIO', 'Medio (Impatto su Servizi Secondari)'), ('BASSO', 'Basso (Danno Minimo)')], default='ALTO', max_length=20, verbose_name="Severità/Criticità (Decisa dall'IR Team)"),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='stato',
            field=models.CharField(choices=[('APERTA', 'Aperta'), ('IN_RISPOSTA', 'In Risposta/Gestione'), ('NOTIFICATA', 'Notificata ACN'), ('CHIUSA', 'Chiusa')], default='APERTA', max_length=20, verbose_name='Stato Notifica'),
        ),
    ]
