# Generated by Django 4.2.26 on 2026-01-04 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_adminreferente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0009_notificaincidente_categoria_incidente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('completato', models.BooleanField(default=False)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_audits', to='user_auth.azienda')),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Security',
                'verbose_name_plural': 'Audit Security',
            },
        ),
        migrations.CreateModel(
            name='SecurityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, verbose_name='Area di Controllo')),
                ('control_id', models.CharField(max_length=50, verbose_name='ID Controllo')),
                ('descrizione', models.TextField(verbose_name='Descrizione Controllo')),
                ('supporto_verifica', models.TextField(blank=True, null=True, verbose_name='Supporto alla Verifica')),
                ('riferimento_iso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Riferimento ISO 27001')),
            ],
            options={
                'verbose_name': 'Controllo Security',
                'verbose_name_plural': 'Controlli Security',
                'ordering': ['control_id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esito', models.CharField(choices=[('SI', 'Sì'), ('NO', 'No'), ('IN_CORSO', 'In Corso'), ('NA', 'Non Applicabile')], default='NO', max_length=10)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note del Consulente')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to='compliance.securityaudit')),
                ('controllo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.securitycontrol')),
            ],
            options={
                'unique_together': {('audit', 'controllo')},
            },
        ),
    ]
