# Generated by Django 4.2.26 on 2026-01-06 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0010_securityaudit_securitycontrol_securityresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'Asset'},
        ),
        migrations.AlterModelOptions(
            name='auditcategoria',
            options={'verbose_name': 'Categoria Audit', 'verbose_name_plural': 'Categorie Audit'},
        ),
        migrations.AlterModelOptions(
            name='auditdomanda',
            options={'verbose_name': 'Domanda Audit', 'verbose_name_plural': 'Domande Audit'},
        ),
        migrations.AlterModelOptions(
            name='auditrisposta',
            options={'verbose_name': 'Risposta Audit', 'verbose_name_plural': 'Risposte Audit'},
        ),
        migrations.AlterModelOptions(
            name='auditsession',
            options={'verbose_name': 'Sessione Audit', 'verbose_name_plural': 'Sessioni Audit'},
        ),
        migrations.AlterModelOptions(
            name='categoriadati',
            options={'verbose_name': 'Categoria Audit', 'verbose_name_plural': 'Categorie Audit'},
        ),
        migrations.AlterModelOptions(
            name='categoriadocumento',
            options={'verbose_name': 'Categoria Documento', 'verbose_name_plural': 'Categorie Documenti'},
        ),
        migrations.AlterModelOptions(
            name='compito',
            options={'verbose_name': 'Compito', 'verbose_name_plural': 'Compiti'},
        ),
        migrations.AlterModelOptions(
            name='documentoaziendale',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documenti'},
        ),
        migrations.AlterModelOptions(
            name='domandachecklist',
            options={'verbose_name': 'Domanda', 'verbose_name_plural': 'Domande'},
        ),
        migrations.AlterModelOptions(
            name='incidente',
            options={'verbose_name': 'Incidente', 'verbose_name_plural': 'Incidenti'},
        ),
        migrations.AlterModelOptions(
            name='paese',
            options={'verbose_name': 'Paese', 'verbose_name_plural': 'Paesi'},
        ),
        migrations.AlterModelOptions(
            name='richiestainteressato',
            options={'verbose_name': 'Richiesta Interessato', 'verbose_name_plural': 'Richiesta Interessati'},
        ),
        migrations.AlterModelOptions(
            name='securityresponse',
            options={'verbose_name': 'Risposta Security', 'verbose_name_plural': 'Risposte Security'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'Software', 'verbose_name_plural': 'Software'},
        ),
        migrations.AlterModelOptions(
            name='soggettointeressato',
            options={'verbose_name': 'Soggetto Interessato', 'verbose_name_plural': 'Soggetti Interessati'},
        ),
        migrations.AlterModelOptions(
            name='trattamento',
            options={'verbose_name': 'Trattamento', 'verbose_name_plural': 'Trattamenti'},
        ),
        migrations.AlterModelOptions(
            name='valutazionetia',
            options={'verbose_name': 'Valutazione TIA', 'verbose_name_plural': 'Valutazioni TIA'},
        ),
        migrations.AlterModelOptions(
            name='videosorveglianza',
            options={'verbose_name': 'Impianto Videosorveglianza', 'verbose_name_plural': 'Impianti Videosorveglianza'},
        ),
        migrations.AddField(
            model_name='auditsession',
            name='archiviata',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allegatonotifica',
            name='descrizione',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='allegatonotifica',
            name='file',
            field=models.FileField(upload_to='csirt_allegati/'),
        ),
        migrations.AlterField(
            model_name='allegatonotifica',
            name='notifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='compliance.notificaincidente'),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='azioni_correttive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='categoria_incidente',
            field=models.CharField(choices=[('RANSOMWARE', 'Ransomware'), ('DDOS', 'Attacco DDOS'), ('PHISHING', 'Phishing'), ('ACCESS_VIOLATION', 'Violazione Account'), ('MALWARE', 'Malware')], default='MALWARE', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='data_incidente',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='data_notifica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='descrizione_danno',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='impatto_stimato',
            field=models.CharField(choices=[('CRITICO', 'Critico'), ('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BASSO', 'Basso')], default='ALTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='playbook_associato',
            field=models.CharField(blank=True, choices=[('RANSOMWARE_P', 'Playbook Ransomware'), ('DDOS_P', 'Playbook DDOS'), ('PHISHING_P', 'Playbook Phishing'), ('GENERIC_P', 'Playbook Generico')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='referente_csirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.referentecsirt'),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='severita_incidente',
            field=models.CharField(choices=[('CRITICO', 'Critico'), ('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BASSO', 'Basso')], default='ALTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='stato',
            field=models.CharField(choices=[('APERTA', 'Aperta'), ('IN_RISPOSTA', 'In Risposta'), ('NOTIFICATA', 'Notificata ACN'), ('CHIUSA', 'Chiusa')], default='APERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='titolo_incidente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificaincidente',
            name='valutazione_rischio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='codice_ipa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codice IPA'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='competenze_documentate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='motivo_esterno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='pc_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Punto di Contatto'),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_cf',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_cognome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_ruolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='ref_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='referente_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csirt_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='sos1_cf',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='sos1_cognome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='sos1_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='sos1_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='sos2_cf',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='sos2_cognome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='sos2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='referentecsirt',
            name='sos2_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='securitycontrol',
            name='riferimento_iso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='securitycontrol',
            name='supporto_verifica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityresponse',
            name='esito',
            field=models.CharField(choices=[('SÌ', 'Sì'), ('NO', 'No'), ('IN_CORSO', 'In Corso'), ('NA', 'Non Applicabile')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='securityresponse',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='amministratore',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videosorveglianza',
            name='tempo_conservazione',
            field=models.CharField(choices=[('24H', '24 Ore'), ('48H', '48 Ore'), ('72H', '72 Ore'), ('7GG', '7 Giorni')], default='24H', max_length=50),
        ),
    ]
