# Generated by Django 4.2.26 on 2026-01-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_alter_asset_options_alter_auditcategoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContattoInternoCSIRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativo', models.CharField(max_length=150, verbose_name='Nominativo')),
                ('ruolo', models.CharField(blank=True, max_length=150, verbose_name='Ruolo')),
                ('telefono_ufficio', models.CharField(blank=True, max_length=50, verbose_name='Telefono Ufficio')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tipo_disponibilita', models.CharField(blank=True, max_length=100, verbose_name='Tipo Disponibilità')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatti_interni_csirt', to='user_auth.azienda', verbose_name='Azienda')),
            ],
            options={
                'verbose_name': 'Contatto Interno CSIRT',
                'verbose_name_plural': 'Contatti Interni CSIRT',
                'ordering': ['nominativo'],
            },
        ),
    ]
