# Generated by Django 4.2.26 on 2026-01-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_alter_asset_options_alter_auditcategoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniSito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_sito', models.CharField(default='HUB Compliance Portal', max_length=200)),
                ('email_contatto', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_config/')),
                ('manutenzione_attiva', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Impostazioni Sito',
                'verbose_name_plural': 'Impostazioni Sito',
            },
        ),
    ]
