# Generated by Django 4.2.25 on 2026-01-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_contattointernocsirt'),
        ('compliance', '0012_impostazionisito'),
    ]

    operations = [
    ]
