# Generated by Django 4.2.25 on 2026-01-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_adminreferente_options_and_more'),
        ('compliance', '0013_merge_0012_contattointernocsirt_0012_impostazionisito'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomandaFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(max_length=255)),
                ('codice', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=255)),
                ('domanda', models.TextField()),
                ('iso_27001', models.CharField(blank=True, max_length=100, null=True)),
                ('fncs', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_tema', models.FloatField(default=1.0)),
                ('peso_domanda', models.FloatField(default=1.0)),
                ('tipo_range', models.CharField(choices=[('Range_1', 'Sì (1) / Parziale (0.5) / No (0)'), ('Range_2', 'Sì (1) / No (0)')], default='Range_1', max_length=10)),
            ],
            options={
                'verbose_name': 'Domanda Questionario Fornitori',
                'verbose_name_plural': 'Domande Questionario Fornitori',
            },
        ),
        migrations.CreateModel(
            name='RispostaQuestionarioFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_risposta', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, null=True)),
                ('data_valutazione', models.DateTimeField(auto_now_add=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutazioni_fornitore', to='user_auth.azienda')),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.domandafornitore')),
            ],
            options={
                'unique_together': {('azienda', 'domanda')},
            },
        ),
    ]
