# Generated by Django 4.2.25 on 2026-01-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_domandafornitore_rispostaquestionariofornitore'),
    ]

    operations = [
        migrations.AddField(
            model_name='domandafornitore',
            name='macro_categoria',
            field=models.CharField(choices=[('GESTIONE', 'Gestione della Sicurezza'), ('IT', 'Sicurezza IT'), ('FISICA', 'Sicurezza Fisica')], default='IT', max_length=20),
        ),
    ]
