# Generated by Django 4.2.25 on 2026-01-17 22:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_alter_auditlog_options_alter_auditlog_azione'),
        ('compliance', '0015_domandafornitore_macro_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ragione_sociale', models.CharField(max_length=255)),
                ('email_contatto', models.EmailField(help_text='Email a cui inviare il link del portale', max_length=254)),
                ('servizio_fornito', models.CharField(help_text='es: Cloud Hosting, Consulenza, ecc.', max_length=255)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stato_valutazione', models.CharField(choices=[('DA_INVIARE', 'Da Inviare'), ('INVIATO', 'Inviato al Fornitore'), ('COMPILATO', 'Compilato dal Fornitore'), ('REVISIONATO', 'Revisionato dal Consulente')], default='DA_INVIARE', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('azienda_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornitori_censiti', to='user_auth.azienda')),
            ],
            options={
                'verbose_name': 'Fornitore Esterno',
                'verbose_name_plural': 'Fornitori Esterni',
            },
        ),
        migrations.CreateModel(
            name='AllegatoFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='fornitori/certificazioni/')),
                ('descrizione', models.CharField(max_length=255)),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificazioni', to='compliance.fornitore')),
            ],
        ),
    ]
