# Generated by Django 4.2.25 on 2026-01-18 15:57

import compliance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_alter_auditlog_options_alter_auditlog_azione'),
        ('compliance', '0017_rispostaquestionariofornitore_fornitore'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegnalazioneWhistleblowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_ticket', models.CharField(default=compliance.models.generate_ticket_code, max_length=10, unique=True)),
                ('categoria', models.CharField(choices=[('PRIVACY', 'Violazione Dati / GDPR'), ('CORRUZIONE', 'Corruzione / Frode'), ('SICUREZZA', 'Sicurezza sul lavoro'), ('ALTRO', 'Altro illecito')], max_length=50)),
                ('oggetto', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('nome_segnalante', models.CharField(blank=True, default='Anonimo', max_length=100, null=True)),
                ('email_contatto', models.EmailField(blank=True, max_length=254, null=True)),
                ('stato', models.CharField(choices=[('APERTA', 'In attesa di revisione'), ('ISTRUTTORIA', 'In corso di valutazione'), ('CHIUSA', 'Archiviata/Risolta')], default='APERTA', max_length=20)),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('risposta_consulente', models.TextField(blank=True, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.azienda')),
            ],
        ),
        migrations.CreateModel(
            name='AllegatoWhistleblowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='whistleblowing/allegati/%Y/%m/%d/')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('segnalazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='compliance.segnalazionewhistleblowing')),
            ],
        ),
    ]
