# Generated by Django 4.2.26 on 2025-11-23 22:17

import colorfield.fields
import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorie Corso',
            },
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Titolo Corso')),
                ('descrizione', models.TextField(verbose_name='Descrizione Completa')),
                ('stato', models.CharField(choices=[('A', 'Attivo'), ('S', 'Sospeso'), ('F', 'Finito')], default='A', max_length=1, verbose_name='Stato')),
                ('durata_ore', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Durata (Ore)')),
                ('is_obbligatorio', models.BooleanField(default=False, verbose_name='Obbligatorio per tutte le aziende')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.categoriacorso', verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Corsi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(verbose_name='Testo Domanda')),
                ('ordine', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Domande Quiz',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='ImpostazioniSito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_piattaforma', models.CharField(default='EasyGDPR', max_length=100, verbose_name='Nome Piattaforma')),
                ('colore_primario', models.CharField(default='#005a9c', max_length=7, verbose_name='Colore Principale (Esadecimale)')),
                ('colore_secondario', colorfield.fields.ColorField(default='#F8F9FA', help_text='Usato per elementi secondari o highlight del tema.', image_field=None, max_length=18, samples=None, verbose_name='Colore Secondario')),
                ('logo_principale', models.ImageField(blank=True, null=True, upload_to=courses.models.upload_path_config, verbose_name='Logo Piattaforma')),
                ('email_service_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Service ID')),
                ('email_public_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Public Key')),
                ('email_private_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Private Key')),
                ('email_template_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Template ID (Benvenuto)')),
                ('email_reset_template_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Reset Template ID')),
                ('email_scadenza_template_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Scadenza Template ID (Corso Scaduto)')),
                ('email_scadenza_compito_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Scadenza Compito ID')),
                ('gemini_api_key', models.CharField(blank=True, help_text='Chiave necessaria per abilitare la generazione di bozze AI.', max_length=255, null=True, verbose_name='Chiave API Google Gemini')),
            ],
            options={
                'verbose_name': 'Impostazioni Sito',
                'verbose_name_plural': 'Impostazioni Sito',
            },
        ),
        migrations.CreateModel(
            name='IscrizioneCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True)),
                ('completato', models.BooleanField(default=False)),
                ('data_completamento', models.DateTimeField(blank=True, null=True)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.corso', verbose_name='Corso')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to=settings.AUTH_USER_MODEL, verbose_name='Studente')),
            ],
            options={
                'verbose_name_plural': 'Iscrizioni Corso',
                'unique_together': {('studente', 'corso')},
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo Modulo')),
                ('contenuto_html', models.TextField(blank=True, null=True, verbose_name='Contenuto HTML')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('durata_minuti', models.PositiveIntegerField(default=30, verbose_name='Durata (Minuti)')),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduli', to='courses.corso', verbose_name='Corso')),
            ],
            options={
                'verbose_name_plural': 'Moduli',
                'ordering': ['corso', 'ordine'],
            },
        ),
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=255, verbose_name='Testo Risposta')),
                ('is_corretta', models.BooleanField(default=False, verbose_name='È la risposta corretta?')),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to='courses.domanda')),
            ],
            options={
                'verbose_name_plural': 'Risposte Quiz',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('punteggio_minimo', models.PositiveIntegerField(default=70, verbose_name='Punteggio Minimo (%)')),
                ('modulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.modulo')),
            ],
            options={
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome File')),
                ('file', models.FileField(upload_to='corso_media/', verbose_name='File Media')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='courses.modulo', verbose_name='Modulo')),
            ],
            options={
                'verbose_name_plural': 'Media Moduli',
            },
        ),
        migrations.AddField(
            model_name='domanda',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domande', to='courses.quiz'),
        ),
        migrations.CreateModel(
            name='Attestato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_univoco', models.CharField(max_length=50, unique=True)),
                ('data_rilascio', models.DateField(auto_now_add=True)),
                ('iscrizione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestato', to='courses.iscrizionecorso')),
            ],
            options={
                'verbose_name_plural': 'Attestati',
            },
        ),
        migrations.CreateModel(
            name='ProgressoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completato', models.BooleanField(default=False)),
                ('data_completamento', models.DateTimeField(blank=True, null=True)),
                ('iscrizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressi', to='courses.iscrizionecorso')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.modulo')),
            ],
            options={
                'verbose_name_plural': 'Progressi Moduli',
                'unique_together': {('iscrizione', 'modulo')},
            },
        ),
    ]
