# Generated by Django 4.2.26 on 2025-11-28 11:17

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazionisito',
            name='template_nomina_csirt',
            field=models.FileField(blank=True, help_text='Carica qui il file .docx con i segnaposto.', null=True, upload_to=courses.models.upload_path_config, verbose_name='Template Word Nomina CSIRT'),
        ),
        migrations.AlterField(
            model_name='impostazionisito',
            name='email_scadenza_template_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Scadenza Template ID'),
        ),
        migrations.AlterField(
            model_name='impostazionisito',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chiave API Google Gemini'),
        ),
    ]
