# Generated by Django 4.2.26 on 2025-12-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_impostazionisito_template_nomina_csirt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazionisito',
            name='dehashed_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dehashed API Key'),
        ),
        migrations.AddField(
            model_name='impostazionisito',
            name='dehashed_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dehashed Username'),
        ),
        migrations.AddField(
            model_name='impostazionisito',
            name='pentest_tools_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pentest-Tools API Key'),
        ),
        migrations.AddField(
            model_name='impostazionisito',
            name='pentest_tools_base_url',
            field=models.URLField(blank=True, default='https://pp.pentest-tools.com', max_length=255, null=True, verbose_name='Pentest-Tools Base URL'),
        ),
        migrations.AddField(
            model_name='impostazionisito',
            name='pentest_tools_scan_path',
            field=models.CharField(blank=True, default='/api/v1/scan', help_text="Percorso endpoint per l'avvio delle scansioni (es. /api/v1/scan).", max_length=255, null=True, verbose_name='Pentest-Tools Scan Path'),
        ),
    ]
