# Generated by Django 4.2.26 on 2025-12-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_impostazionisito_template_nomina_csirt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazionisito',
            name='nessus_access_key',
            field=models.CharField(blank=True, help_text='Chiave di accesso generata in Nessus (Settings -> My Account -> API Keys).', max_length=255, null=True, verbose_name='Nessus Access Key'),
        ),
        migrations.AddField(
            model_name='impostazionisito',
            name='nessus_secret_key',
            field=models.CharField(blank=True, help_text='Chiave segreta generata in Nessus.', max_length=255, null=True, verbose_name='Nessus Secret Key'),
        ),
        migrations.AddField(
            model_name='impostazionisito',
            name='nessus_url',
            field=models.URLField(default='https://localhost:8834', help_text='Indirizzo del server Nessus per la scansione asset.', max_length=255, verbose_name='URL Server Nessus'),
        ),
    ]
