# Generated by Django 4.2.26 on 2026-01-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_impostazionisito_nessus_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazionisito',
            name='dehashed_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='impostazionisito',
            name='dehashed_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
