# Generated by Django 4.2.26 on 2026-01-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_impostazionisito_pentest_tools_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazionisito',
            name='viewdns_api_key',
            field=models.CharField(blank=True, help_text='Chiave API per i servizi di ViewDNS.info', max_length=255, null=True, verbose_name='ViewDNS API Key'),
        ),
    ]
