# Generated by Django 4.2.25 on 2026-01-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_impostazionisito_viewdns_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazionisito',
            name='emailjs_template_id_allerta',
            field=models.CharField(blank=True, help_text="L'ID del template EmailJS specifico per i tentativi di brute force.", max_length=100, null=True, verbose_name='ID Template Allerta Intrusione'),
        ),
        migrations.AlterField(
            model_name='impostazionisito',
            name='nome_piattaforma',
            field=models.CharField(default='HubCompliance', max_length=100, verbose_name='Nome Piattaforma'),
        ),
    ]
