# Generated by Django 4.2.25 on 2026-01-19 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0010_merge_0008_azienda_mod_extra_modules_0009_alter_auditlog_options_alter_auditlog_azione'),
        ('courses', '0008_impostazionisito_email_fornitori_template_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFormazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_corso', models.CharField(max_length=255)),
                ('data_completamento', models.DateField(default=django.utils.timezone.now)),
                ('durata_ore', models.DecimalField(decimal_places=2, help_text='Ore di formazione', max_digits=5)),
                ('fonte', models.CharField(choices=[('A', 'Automatico (Piattaforma)'), ('M', 'Manuale (Esterno)')], default='M', max_length=1)),
                ('note', models.TextField(blank=True, help_text='Eventuali note o riferimenti esterni', null=True)),
                ('documento_attestato', models.FileField(blank=True, null=True, upload_to='attestati_manuali/')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_formazione', to='user_auth.azienda')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dipendente')),
            ],
            options={
                'verbose_name': 'Voce Registro Formazione',
                'verbose_name_plural': 'Registro Formazione Aziendale',
                'ordering': ['-data_completamento'],
            },
        ),
    ]
