# Generated by Django 4.2.26 on 2025-12-23 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0007_alter_adminreferente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMonitorato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Es: Server Produzione 01', max_length=100)),
                ('tipologia', models.CharField(choices=[('SERVER', 'Server Fisico/VM'), ('DB', 'Database'), ('WEB', 'Sito Web / API'), ('NETWORK', 'Apparato di Rete (Firewall/Switch)')], default='SERVER', max_length=20)),
                ('indirizzo_ip', models.GenericIPAddressField(help_text="Indirizzo IP dell'asset")),
                ('porta_monitoraggio', models.PositiveIntegerField(default=9100, help_text="Porta dell'exporter (es. 9100 per Node Exporter)")),
                ('is_attivo', models.BooleanField(default=True, help_text='Indica se il monitoraggio è attivo')),
                ('soglia_allarme_cpu', models.PositiveIntegerField(default=90, help_text="Percentuale CPU per far scattare l'allerta")),
                ('note_tecniche', models.TextField(blank=True, null=True)),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('ultima_modifica', models.DateTimeField(auto_now=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_monitorati', to='user_auth.azienda')),
            ],
            options={
                'verbose_name': 'Asset Monitorato',
                'verbose_name_plural': 'Assets Monitorati',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LogMonitoraggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stato_up', models.BooleanField(default=True)),
                ('messaggio_errore', models.TextField(blank=True, null=True)),
                ('durata_down', models.DurationField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.assetmonitorato')),
            ],
        ),
    ]
